pull_request_rules:
  - name: rebase pull requests labeled with `rebase`, once
    conditions:
      - label = rebase
    actions:
      rebase: {}
      label:
        remove:
          - rebase
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
          - author=dependabot[bot]
          - author=github-actions[bot]
          - author= ProverbialPennance
      - or:
          - label=dependencies
          - label=update
      - check-success=Build
      - check-success=Format
      - or:
          - check-success=Checks
          - check-neutral=Checks
          - check-pending=Checks
          - check-timed-out=Checks
          - check-stale=Checks
    actions:
      merge:
        method: rebase
      delete_head_branch:
