pull_request_rules:
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
          - author=dependabot[bot]
          - author=github-actions[bot]
      - or:
          - label=dependencies
          - label=update
      - check-success=Build

    actions:
      merge:
        method: rebase
      delete_head_branch:
