name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/*.yml
  merge_group:
  pull_request:
    branches: ["*"]
    paths:
      - "**.nix"
      - flake.lock
      - .github/workflows/*.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: [X64, Linux]
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= just-one-more-cache.cachix.org-1:4nShcKEgcUEVlJqKFrgDwoGfqLnw5KPG4UDTV02jnr4=
            substituters = https://cache.nixos.org/ https://just-one-more-cache.cachix.org/
      - uses: yaxitech/nix-install-pkgs-action@v7
        with:
          packages: "nixpkgs#omnix, github:juspay/cachix-push"
      - uses: cachix/cachix-action@v17
        with:
          name: just-one-more-cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - if: env.BRANCH_NAME == 'main'
        run: |
          # build (main branch)
          set -euxo pipefail
          om ci run .#packages --include-all-dependencies --results=om.json -- --show-trace

          declare -A derivationArray=()

          _triplet=$(jq -rc '.systems[]' ./om.json)
          triplet=${_triplet//\"/}

          derivationsMap=$(jq -rc 'del(.result.ROOT.build.byName."vm-test-run-Factorio", .result.ROOT.build.byName."vm-test-run-dotnet-binfmt_misc-integration-test") | .result.ROOT.build.byName' ./om.json \
            | sed -r 's/(\{|\})//g' \
            | tr ',' '\n' \
            | tr ':' ',')

          while IFS="," read -r name _path; do
            key=${name//\"/}
            path=${_path//\"/}
            derivationArray["$key"]="$path"
          done < <(echo "$derivationsMap")

          for key in "${!derivationArray[@]}"; do
            cachix pin -v just-one-more-cache "${{env.BRANCH_NAME}}-$triplet-$key" "${derivationArray[$key]}" --keep-revisions 1
          done
      - if: env.BRANCH_NAME != 'main'
        name: build (${{ github.head_ref || github.ref_name }})
        run: |
          # build ("${{ env.BRANCH_NAME }}" branch)
          set -euxo pipefail
          om ci run .#packages --include-all-dependencies -- --show-trace | xargs cachix push just-one-more-cache
